### ISSUE TITLE
2.10.1 tarball does not contain dependencies

### ISSUE THREAD

**Issue by tkelman** [coin-or/OS#1]
It looks like maybe a pkgsource tarball was uploaded to http://www.coin-or.org/download/source/OS/OS-2.10.1.tgz instead of a full-with-deps tarball? cc @tkralphs

**Comment by tkralphs** [comment]
I'm not sure exactly what happened here, but I'm going to guess it's my fault :). There were tarballs for both OS and Dip that had this problem. They were generated at 17:15 on 10-1-2015, which means they were not generated by the automatic scripts. I have a vague recollection of running the generation script manually for some reason, but I must have give the wrong arguments or something. I just deleted the incorrect tarballs and they should be re-generated properly when the nightly scripts run tonight. If you notice that they're not, please let me know.

**Comment by tkralphs** [comment]
Looks like it's OK now.

**Comment by tkelman** [comment]
Thanks @tkralphs!
