### ISSUE TITLE
Bonmin test failed

### ISSUE THREAD

**Issue by sagitter** [coin-or/OS#71]
Hi all.

Bonmin test is failing with this error:

```
TEST 13: Bonmin solver on bonminEx1.osil

call the COIN - Bonmin Solver for bonminEx1
lt-unitTest: BonHeuristicDiveMIP.cpp:133: virtual int Bonmin::HeuristicDiveMIP::solution(double&, double*): Assertion `isNlpFeasible(minlp, primalTolerance)' failed.
make[2]: *** [Makefile:708: test] Aborted (core dumped)
```

`Bonmin` and `OS` are compiled against `Ipopt-3.14.3` in Fedora 36 (development branch) with `GCC-11.2.1`
Full build log: [here](https://download.copr.fedorainfracloud.org/results/sagitter/ForTesting/fedora-rawhide-x86_64/02824192-coin-or-OS/build.log.gz)

**Comment by svigerske** [comment]
We added a fix to Bonmin/master for this: https://github.com/coin-or/Bonmin/issues/24

**Comment by sagitter** [comment]
Thank you.
